# Generated by Django 5.1.4 on 2025-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='Calle Alegria 123', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='Talarrubias', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='code_postal',
            field=models.CharField(default=28080, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='España', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='dni',
            field=models.CharField(default='12345678A', max_length=10),
            preserve_default=False,
        ),
    ]
