# Generated by Django 5.1.4 on 2025-02-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_address_patient_city_patient_code_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alergias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patologias',
            field=models.JSONField(default=list),
        ),
    ]
