# Generated by Django 5.1.4 on 2025-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_alergias_patient_notas_patient_patologias'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pdf_firmado',
            field=models.FileField(blank=True, null=True, upload_to='signed_pdfs/'),
        ),
    ]
