# Generated by Django 5.1.4 on 2025-02-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_pdf_firmado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='pdf_firmado',
            new_name='pdf_firmado_general',
        ),
        migrations.AddField(
            model_name='patient',
            name='pdf_firmado_inyecciones',
            field=models.FileField(blank=True, null=True, upload_to='signed_pdfs/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pdf_firmado_menor',
            field=models.FileField(blank=True, null=True, upload_to='signed_pdfs/'),
        ),
    ]
