# Generated by Django 5.1.4 on 2025-03-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_pdf_firmado_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pdf_firmado_general',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf_PD_firmados/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pdf_firmado_inyecciones',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf_MI_firmados/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pdf_firmado_menor',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf_CM_firmados/'),
        ),
    ]
