# Generated by Django 5.1.4 on 2025-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patientdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocument',
            name='file',
            field=models.FileField(upload_to='patient_documents/'),
        ),
    ]
