# Generated by Django 5.1.4 on 2025-03-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_patientdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pdf_firmado_general',
            field=models.FileField(blank=True, null=True, upload_to='pdf_PD_firmados/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pdf_firmado_inyecciones',
            field=models.FileField(blank=True, null=True, upload_to='pdf_MI_firmados/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pdf_firmado_menor',
            field=models.FileField(blank=True, null=True, upload_to='pdf_CM_firmados/'),
        ),
    ]
