# Generated by Django 5.1.4 on 2025-05-27 10:27

import django.core.validators
import django.db.models.deletion
import patients.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_remove_activity_patients'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('citas', '0015_remove_citas_patient'),
        ('patients', '0013_alter_patient_pdf_firmado_general_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocument',
            name='patient',
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alergias', models.BooleanField(default=False)),
                ('patologias', models.JSONField(default=list)),
                ('notas', models.TextField(blank=True, null=True)),
                ('pdf_firmado_general', models.FileField(blank=True, null=True, upload_to=patients.models.upload_pdf_firmado_general, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('pdf_firmado_menor', models.FileField(blank=True, null=True, upload_to=patients.models.upload_pdf_firmado_menor, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('pdf_firmado_inyecciones', models.FileField(blank=True, null=True, upload_to=patients.models.upload_pdf_firmado_inyecciones, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='auth.group')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('grupo', 'email')},
            },
        ),
        migrations.CreateModel(
            name='PacienteDocumentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=patients.models.patient_doc_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='patients.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientDocument',
        ),
    ]
