# Generated by Django 5.1.4 on 2025-05-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_remove_patientdocument_patient_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='patologias',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
