# Generated by Django 5.1.4 on 2025-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='country',
            field=models.CharField(default='España', max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='dni',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='first_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='postal_code',
            field=models.CharField(default=True, max_length=10),
        ),
    ]
