# Generated by Django 5.1.4 on 2025-01-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_address_worker_country_worker_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='address',
            field=models.CharField(default='Sin dirección', max_length=255),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='last_name',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='postal_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
