# Generated by Django 5.1.4 on 2025-01-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_worker_address_alter_worker_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='dni',
            field=models.CharField(default='12345678A', max_length=20),
        ),
    ]
