# Generated by Django 5.1.4 on 2025-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_worker_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
