# Generated by Django 5.1.4 on 2025-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_remove_worker_branch_worker_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='worker_photos/'),
        ),
    ]
