# Generated by Django 5.1.4 on 2025-02-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_worker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
