# Generated by Django 5.1.4 on 2025-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_worker_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='registro_jornada',
            field=models.FileField(blank=True, null=True, upload_to='registro_jornada/'),
        ),
    ]
