# Generated by Django 5.1.4 on 2025-02-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_worker_registro_jornada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='country',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='postal_code',
        ),
    ]
