# Generated by Django 5.1.4 on 2025-02-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0010_remove_worker_address_remove_worker_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='registro_jornada',
        ),
        migrations.AddField(
            model_name='worker',
            name='registro_jornada_admin',
            field=models.FileField(blank=True, null=True, upload_to='registro_jornada_admin/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='registro_jornada_usuario',
            field=models.FileField(blank=True, null=True, upload_to='registro_jornada_usuario/'),
        ),
    ]
