# Generated by Django 5.1.4 on 2025-02-18 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0011_remove_worker_registro_jornada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='registro_jornada_admin',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='registro_jornada_usuario',
        ),
        migrations.CreateModel(
            name='PDFRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='registro_jornada/')),
                ('is_admin_upload', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_registros', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_registros', to='workers.worker')),
            ],
        ),
    ]
