# Generated by Django 5.1.4 on 2025-02-21 16:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0012_remove_worker_registro_jornada_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfregistro',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
