# Generated by Django 5.1.4 on 2025-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_alter_pdfregistro_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfregistro',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='registro_jornada/'),
        ),
    ]
