# Generated by Django 5.1.4 on 2025-03-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0014_alter_pdfregistro_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfregistro',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/registro_jornada/'),
        ),
    ]
