# Generated by Django 5.1.4 on 2025-05-29 10:21

import workers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0016_alter_pdfregistro_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfregistro',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=workers.models.upload_to_registro),
        ),
    ]
