# Generated by Django 5.1.4 on 2025-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='formacion',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='formacion',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
    ]
