# Generated by Django 5.1.4 on 2025-01-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('workers', '0004_alter_worker_dni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('recurrence_days', models.JSONField(default=list)),
                ('duration', models.IntegerField(choices=[(1, '1 mes'), (6, '6 meses')], default=1)),
                ('monitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitored_activities', to='workers.worker')),
                ('patients', models.ManyToManyField(to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
