# Generated by Django 5.1.4 on 2025-01-11 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_remove_activity_duration_activity_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_months',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
