# Generated by Django 5.1.4 on 2025-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_activity_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_months',
            field=models.IntegerField(default=1),
        ),
    ]
