# Generated by Django 5.1.4 on 2025-01-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_alter_activity_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
