# Generated by Django 5.1.4 on 2025-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_alter_activity_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
