# Generated by Django 5.1.4 on 2025-01-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_remove_activity_duration_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
