# Generated by Django 5.1.4 on 2025-03-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_alter_activity_end_time_alter_activity_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
