# Generated by Django 5.1.4 on 2025-05-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_alter_activity_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='patients',
        ),
    ]
