# Generated by Django 5.1.4 on 2025-05-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_remove_activity_patients'),
        ('patients', '0014_remove_patientdocument_patient_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pacientes',
            field=models.ManyToManyField(to='patients.paciente'),
        ),
    ]
