# Generated by Django 5.1.4 on 2025-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(default='default_photo.jpg', null=True, upload_to='photo_workers/'),
        ),
    ]
