# Generated by Django 5.1.4 on 2025-02-21 16:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_userinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_photo.jpg', max_length=255, null=True, verbose_name='photo'),
        ),
    ]
