# Generated by Django 5.1.4 on 2025-03-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_alter_userinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='media/foto_perfil/'),
        ),
    ]
