# Generated by Django 5.1.4 on 2025-03-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_alter_userinfo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone_number_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='whatsapp_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
