# Generated by Django 5.1.4 on 2025-03-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_userinfo_phone_number_id_userinfo_whatsapp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', null=True, upload_to='foto_perfil/'),
        ),
    ]
