# Generated by Django 5.1.4 on 2025-04-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0007_alter_userinfo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone_number_id',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='whatsapp_token',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twilio_integration_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twilio_whatsapp_service_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='whatsapp_business_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
