# Generated by Django 5.1.4 on 2025-05-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0008_remove_userinfo_phone_number_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
