# Generated by Django 5.1.4 on 2025-05-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0009_alter_userinfo_photo_alter_userinfo_segundo_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
