# Generated by Django 5.1.4 on 2025-03-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0011_citas_bizum_citas_efectivo_citas_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='citas.citas')),
            ],
        ),
    ]
