# Generated by Django 5.1.4 on 2025-03-24 15:03

import django.db.models.deletion
import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_factura_total'),
        ('userinfo', '0006_userinfo_phone_number_id_userinfo_whatsapp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(default=facturacion.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to='userinfo.userinfo'),
        ),
    ]
