# Generated by Django 5.1.4 on 2025-03-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_factura_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicial', models.CharField(default='1', max_length=50)),
            ],
        ),
    ]
