# Generated by Django 5.1.4 on 2025-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_configuracionfactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionfactura',
            name='numero_inicial',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.IntegerField(),
        ),
    ]
