# Generated by Django 5.1.4 on 2025-03-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_alter_configuracionfactura_numero_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
