# Generated by Django 5.1.4 on 2025-05-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0017_remove_citas_paciente_remove_citas_user_and_more'),
        ('facturacion', '0008_alter_factura_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='citas.cita'),
        ),
    ]
