# Generated by Django 5.1.4 on 2025-01-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_configuracionfinanzas_transaccion_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='usuario',
            new_name='user',
        ),
    ]
