# Generated by Django 5.1.4 on 2025-01-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_citas_cotizada'),
        ('finanzas', '0003_rename_usuario_transaccion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.citas'),
        ),
    ]
