# Generated by Django 5.1.4 on 2025-01-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_transaccion_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cita_registrada',
            field=models.BooleanField(default=False),
        ),
    ]
