# Generated by Django 5.1.4 on 2025-03-11 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_activity_precio'),
        ('finanzas', '0005_transaccion_cita_registrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfinanzas',
            name='precio_actividad_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio base de la actividad'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.activity'),
        ),
    ]
