# Generated by Django 5.1.4 on 2025-01-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_citas_patient'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='patients.patient'),
        ),
    ]
