# Generated by Django 5.1.4 on 2025-01-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_alter_citas_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
