# Generated by Django 5.1.4 on 2025-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_citas_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='cotizada',
            field=models.BooleanField(default=False),
        ),
    ]
