# Generated by Django 5.1.4 on 2025-03-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_citas_cotizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='bizum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citas',
            name='efectivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='citas',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
