# Generated by Django 5.1.4 on 2025-05-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_citas_bizum_citas_efectivo_citas_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_global', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='citas',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=10),
        ),
    ]
