# Generated by Django 5.1.4 on 2025-05-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_configuracionpreciocita_alter_citas_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='configuracionpreciocita',
            name='precio_global',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
