# Generated by Django 5.1.4 on 2025-05-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0014_alter_citas_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='patient',
        ),
    ]
