# Generated by Django 5.1.4 on 2025-05-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0015_remove_citas_patient'),
        ('patients', '0014_remove_patientdocument_patient_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='patients.paciente'),
        ),
    ]
