# Generated by Django 5.1.4 on 2025-05-28 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0016_citas_paciente'),
        ('patients', '0014_remove_patientdocument_patient_paciente_and_more'),
        ('workers', '0016_alter_pdfregistro_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='user',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='worker',
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comenzar', models.TimeField()),
                ('finalizar', models.TimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=25, max_digits=10)),
                ('cotizada', models.BooleanField(default=False)),
                ('irpf', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('bizum', 'Bizum'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_pacientes', to='patients.paciente')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_worker', to='workers.worker')),
            ],
        ),
    ]
