# Generated by Django 5.1.4 on 2025-05-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0017_remove_citas_paciente_remove_citas_user_and_more'),
        ('facturacion', '0009_alter_factura_cita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Citas',
        ),
    ]
