# Generated by Django 5.1.4 on 2025-03-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(default='#FFEE8C', max_length=20)),
                ('is_important', models.BooleanField(default=False)),
            ],
        ),
    ]
