# Generated by Django 5.1.4 on 2025-03-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
